### ISSUE TITLE
Controller flag in wc_sessionPropose

### ISSUE THREAD

**Issue by jakubuid** [WalletConnect/walletconnect-specs#13]
// wc_sessionPropose params
```
{
    "relay": [
        {
            "protocol": string,
            "data": string // Optional
        },
    ],
    "blockchainProposed": {
        "auth": string, // Optional
        "chains": [string] // CAIP-2 chain IDs
    },
    "permissions": {
        "jsonrpc": {
            "methods": [string]
        },
        "notifications": {
            "types": [string]
        }
    },
    "proposer": {
        "publicKey": string,
        "controller": bool,
        "metadata": {
            "name": string,
            "description": string,
            "url": string,
            "icons": [string]
        }
    }
}

```
We agreed on the session propose request, shown above.

**Questions:**
1. Since we agreed to remove the controller flag at all, should we keep this flag in proposer? 
2. Why the **relay** param is json array? Imo we should keep it as an json object.

**Comment by jakubuid** [comment]
@WalletConnect/sdk-team  ⬆️

**Comment by llbartekll** [comment]
1. controller flag shouldn't be there take a look at doc.
2. it is in an array because proposer can support multiple protocols like waku/webRTC and wallet can chose one of many that it supports

**Comment by jakubuid** [comment]
This is actually already merged and is from our github doc.

**Comment by llbartekll** [comment]
so I believe it is incorrect

**Comment by jakubuid** [comment]
We should change "relay" to "relays".
Controller fag should be removed.

**Comment by dukevantreta** [comment]
Controller flag removed and `relay` renamed to `relays`: https://github.com/WalletConnect/sdk-team/pull/14
