### ISSUE TITLE
wc_sessionPropose ttl

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/walletconnect-specs#15]
In our current version of `wc_sessionPropose` request we do not have `ttl` or `expiry`.  In order to achieve absolute timestamp, should we add it in `wc_sessionPropose` or `wc_sessionSettle` request?

@WalletConnect/sdk-team

**Comment by llbartekll** [comment]
ok I see `TTL sent in Session Proposal` so we just need to update the doc

**Comment by llbartekll** [comment]
There is a couple of issues and inconveniences in implementation with above approach to expiry time. 
I had a call with @jakobuid and we have reached a consensus that the best approach will be as follow:
1. remove `ttl` from `wc_sessionPropose` request
2. add `expiryTimestamp` property to `wc_sessionSettle` request, so the timestamp is computed on controller side
3. proposer settles session considering `expiryTimestamp` set by responder

`expiryTimestamp` seems to be more accurate name then `ttl` when talking about absolute timestamp.
@WalletConnect/sdk-team

**Comment by jakubuid** [comment]
☝️ 
Agreed on that.
What is more, with this approach there is no need to store proposals (at least on kotlin side), because session expiry comes from `wc_sessionSettle`.
Once proposer receives the session settle, acknowledged session is saved into local storage with proper expirytimestamp and params.

**Comment by dukevantreta** [comment]
We just need to remember to add sanity checks to avoid absurd timestamps

**Comment by jakubuid** [comment]
**EDIT:** instead of having `expiryTimestamp` we use `expiry` in the `wc_sessionSettle`.
