### ISSUE TITLE
Pairing metadata

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/walletconnect-specs#21]
Currently, in a `wc_sessionPropose` we are sending proposers metadata:
```
    "proposer": {
        "publicKey": string,
        "metadata": {
            "name": string,
            "description": string,
            "url": string,
            "icons": [string]
        }
    },
```

and wallet is responding with only it's pub_key:
```   
 "responder": {
        "publicKey": string
    }
```
As I can recall we've been discussing that wallet metadata should be updated on dapp side with session settle request.

I think it would make more sense if a wallet responds with its metadata and dapp sends only its pub key. here is why:
1. currently wallet never displays pairing metadata so maybe it is no necessary to pass it.
2. if we assume that the pairing is shared between browser's tabs with iframe, the pairing metadata would be confusing for a wallet. It would associate the whole pairing with only one dapp.
3. wallet could share its pairing metadata in `wc_sessionPropose` response and that metadata is always identifying the same app.
4. updating pairing metadata with session metadata is inconvenient and will be causing issues, for example, Trust Wallet want to have a single pairing and many sessions for different wallets, if we are updating pairing metadata with switched wallet's session metadata it will be causing confusion. 

@WalletConnect/sdk-team

**Comment by jakubuid** [comment]
Yes this is required.
We also have to remember that wallet metadata should be send both when wallet approves and rejects a session.
Once the session propose response is received, dApp should update a peer/wallet metadata.

The below payload should be added to Success (approval) and Error (rejection) responses:

```
 "responder": {
        "publicKey": string,
        "metadata": {
            "name": string,
            "description": string,
            "url": string,
            "icons": [string]
        }
    }
```

Success (approval) = relay, responder (pubKey, walletMetadata)
Error (rejection) = code, message, data (walletMetadata)

Following the JsonRpc schema we could use `data` field in the Error response, ref link: https://www.jsonrpc.org/specification#response_object

**Comment by llbartekll** [comment]
good catch, or we could forget about `activating` an `inactive` pairing on propose rejection.

**Comment by jakubuid** [comment]
This is also an option.

**Comment by chadyj** [comment]
@WalletConnect/sdk-team Any update?
