### ISSUE TITLE
Handling the lack of an internet connection

### ISSUE THREAD

**Issue by jakubuid** [WalletConnect/walletconnect-specs#22]
We should consider the default behaviour for the SDKs whenever there is no Internet connection and user calls one of the public methods. Such case is important on mobile apps where the connection could be unstable.

 Given that users call the public sdk methods and there is no Internet connection:

-  **Option 1 :** Engine detects whether there is an Internet connection before publishing request/response. If there is no Internet connection SDK throws and error to the user and request or response is not published.

- **Option 2 :** Engine allows calling the relay publish method. Then Relay cannot publish a message, so it caches the requests/responses. When Relay detects that the Internet connection is back, it takes the cached requests/responses and publishes them in proper order.

- **Option 3 :** ?

@WalletConnect/sdk-team let's discuss options and choose the most appropriate one.

**Comment by llbartekll** [comment]
That is an important issue to talk about, I think that it is can also be related to how we handle other relayer errors. 
I believe that "Remote Signer" should not be necessarily aware of the network conditions and treat network loss as another  "relayer error". So then it stays kind of "Transport agnostic".

Good brainstorming topic for Barcelona ;)

**Comment by chadyj** [comment]
@llbartekll @jakobuid Did you end up discussing this in Barcelona?

**Comment by llbartekll** [comment]
I feel like there is no full agreement on this, yet

**Comment by jakubuid** [comment]
Indeed, there is no agreement yet. I propose to discuss it on our Monday's sync meeting.
I'll remember to add it to agenda.

**Comment by dukevantreta** [comment]
Discussed suggestion: Specify a cache policy per request, handling immediate failure and request caching / retrial differently for each type of request.

**Comment by chadyj** [comment]
Discussed in the team meeting:

Consensus is go for Option 1. It makes the most sense for auth.

But consider other options and use cases for messaging and notifications.

TTL is an optional parameter on publish relay API. When it is undefined it should fail when offline.
When defined it should retry within TTL client side.

This is an Apple API for HTTPS requests cache policy, can be useful as a reference: https://developer.apple.com/documentation/foundation/nsurlrequest/cachepolicy

**Comment by chadyj** [comment]
@llbartekll @MisterVants Are you handling this? Create an issue?

**Comment by llbartekll** [comment]
@chadyj if you like you can create an issue, 
to have a policy will be more relevant when we start sharing relay client with messaging sdk. Currently I am working on fixing approach for auth. It is somehow related to https://github.com/WalletConnect/WalletConnectSwiftV2/issues/168

**Comment by chadyj** [comment]
Closing, since we now have Swift and Kotlin issues 

https://github.com/WalletConnect/WalletConnectSwiftV2/issues/190
https://github.com/WalletConnect/WalletConnectKotlinV2/issues/8

@bkrem @IljaDaderko Is anything required on the JS side?
