### ISSUE TITLE
Update / Upgrade changes

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/walletconnect-specs#23]
To simplify the permissions and account changes it should be consistent that both overwrite instead of permissions which currently does unions

On top of this we flatten the data structure to have methods, notifications and accounts

To this we introduce three new methods:
- wc_sessionUpdateAccounts
- wc_sessionUpdateMethods
- wc_sessionUpdateEvents

For all these methods they use overwrite (rather than union) just like wc_sessionUpdate

**Comment by pedrouid** [comment]
Treat expiry as an update event

Rename wc_sessionExtend to wc_sessionUpdateExpiry

**Comment by jakubuid** [comment]
New client sync payloads:

**wc_sessionUpdateAccounts:**
```
// request
interface WCSessionUpdateAccountsRequest {
  id: number;
  jsonrpc: "2.0";
  method: "wc_sessionUpdateAccounts";
  params: {
    accounts: List<String>;
  };
}

// response
interface WCSessionUpdateAccountsResponse {
  id: number;
  jsonrpc: "2.0";
  result: true;
}
```

 **wc_sessionUpdateMethods:**
```
// request
interface WCSessionUpdateMethodsRequest {
  id: number;
  jsonrpc: "2.0";
  method: "wc_sessionUpdateMethods";
  params: {
    methods: List<String>;
  };
}

// response
interface WCSessionUpdateMethodsResponse {
  id: number;
  jsonrpc: "2.0";
  result: true;
}
```

** wc_sessionUpdateEvents:**
```
// request
interface WCSessionUpdateEventsRequest {
  id: number;
  jsonrpc: "2.0";
  method: "wc_sessionUpdateEvents";
  params: {
    names: List<String>;
  };
}

// response
interface WCSessionUpdateEventsResponse {
  id: number;
  jsonrpc: "2.0";
  result: true;
}
```

** wc_sessionUpdateExpiry:**
```
// request
interface WCSessionUpdateExpiryRequest {
  id: number;
  jsonrpc: "2.0";
  method: "wc_sessionUpdateExpiry";
  params: {
    expiry: Long;
  };
}

// response
interface WCSessionUpdateExpiryResponse {
  id: number;
  jsonrpc: "2.0";
  result: true;
}
```

New proposed structures of update requests ☝️ 

One suggestion, we should consider flattening the SessionSettle and SessionPropose as well. Now we send the SessionPermissions object, instead we could just send jsonRpc and methods without nesting.

@WalletConnect/sdk-team any thoughts?

**Comment by llbartekll** [comment]
Agree, I’ve flattened propose and settle already. We can schedule some inter platform manual testing.

**Comment by jakubuid** [comment]
Sure, I should be ready by the end of this week. I'll let you know.

**Comment by llbartekll** [comment]
previously we have had following protocol error codes for given errors:
```
        case .unauthorizedUpdateRequest: return 3003
        case .unauthorizedUpgradeRequest: return 3004
        case .unauthorizedExtendRequest: return 3005
```
Now we can either have one method for all unauthorized updates or new code for each, like:
```
        case .unauthorizedUpdateAccountsRequest: return 3003
        case .unauthorizedUpdateMethodsRequest: return 3004
        case .unauthorizedUpdateEventsRequest: return 3005
        case .unauthorizedUpdateExpiryRequest: return 3006
```

second approach makes more sense to me but still we need to be consistent with error codes.

@WalletConnect/sdk-team

**Comment by jakubuid** [comment]
I'm for the second approach. So we flatten permissions, let's also have decoupled error codes.

**Comment by jakubuid** [comment]
The same applies to invalid request error codes.

Before:
```
is Error.InvalidUpdateRequest -> 1003
is Error.InvalidUpgradeRequest -> 1004
is Error.InvalidExtendRequest -> 1005
```

Now:
```
is Error.InvalidUpdateAccountsRequest -> 1003
is Error.InvalidUpdateMethodsRequest -> 1004
is Error.InvalidUpdateEventsRequest -> 1005
is Error.InvalidUpdateExpiryRequest -> 1006
```

I send them whenever validation of request fails.

**Comment by llbartekll** [comment]
another one:
```
        case .unauthorizedNotificationType: return 3002
```

we can change for:
```
        case .unauthorizedEventType: return 3002
```
