### ISSUE TITLE
Manual Release Testing Plan

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/walletconnect-specs#36]
Hey @WalletConnect/sdk-team!

So far we have had an adhoc release testing plan, but as we gear up for beta 100 and beyond, we should codify proper release testing standards.  The goal is to catch any bugs or issues, and make every effort to ensure the public release is issue-free.

The last step is device testing, and making sure we test in various combinations (eg mobile<>mobile, mobile<>desktop, device<>device, etc).

Please help us and put together testing flows that are to be manually tested.  
https://docs.google.com/document/d/12qgzijIf4enfFxcJt3B0BUJpfsXhL9s47QhVr4kKZ4A/edit#

@Elyniss will be owning this, and reaching out to ensure all teams have been consulted and reviewed.

**Comment by chadyj** [comment]
Also as a follow up, is there any interest in doing automated device testing with something like [Firebase Test Lab](https://firebase.google.com/docs/test-lab)?

**Comment by jakubuid** [comment]
Some time ago I created this doc with wallet test cases: https://docs.google.com/document/d/1e79YJhhL2AHnztEhyQgvsLVgAz99tLz9Kd_YJ88qm8U/edit
Might be a bit outdated once a new sample wallet is ready but we anyway could find it helpful.

**Comment by llbartekll** [comment]
the doc looks like a good start.
I like the idea with Firebase test Lab but just wonder how much time it would take to set it up and to maintain it later.

**Comment by chadyj** [comment]
Closing.
Plan is in place https://docs.google.com/document/d/12qgzijIf4enfFxcJt3B0BUJpfsXhL9s47QhVr4kKZ4A/edit#

And testing sessions have been done.
