### ISSUE TITLE
EncryptionPayload

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/walletconnect-specs#4]
previously we've been serialising messages to following format:
`\(iv)\(publicKey)\(mac)\(cipherText)`
as for pairing we do not have any `pubKey` can we assume that all messages will have format like:
`\(iv)\(mac)\(cipherText)`
for every encrypted message?
`pubKey` has little if any value here.

**Comment by llbartekll** [comment]
@WalletConnect/sdk-team

**Comment by jakubuid** [comment]
For me it makes sense. If we agree that we remove pubKey for all encrypted messages it should work.
Pubkey only increases the data payload length.

**Comment by pedrouid** [comment]
Actually I would need to read a bit more on this because there are advantages to including the pubKey in the encryption payload

Let's prioritize other protocol changes rather than changing encryption first

**Comment by llbartekll** [comment]
@pedrouid honestly, I have already changed it as it gives generic approach to symKey and agreementKey. there is no pubKey for raw symKey for pairing.
What are the adventages? I understand that in symmetric cryptography there is no signatures but hmacs so, there is no way of proving which participant has send a message. both peers could set any pubKey there. What could be other reasons? 🤔

**Comment by llbartekll** [comment]
and having different serialised message formats will be very inconvenient and error prone. additionally it will give coupling from KMS to WalletConnect, which is already decoupled in swift

**Comment by pedrouid** [comment]
We are introducing a lot of breaking changes to the Engine

But this is a breaking change outside of the engine

If we intend to break encryption then we should use versioning as well

**Comment by pedrouid** [comment]
> and having different serialised message formats will be very inconvenient and error prone. additionally it will give coupling from KMS to WalletConnect, which is already decoupled in swift 

Honestly my approach was to hash the symKey to act as a pubKey

Don't forget that we use the pubKey to get the MAC

Without it then we are going to change our ECIES implementation

**Comment by llbartekll** [comment]
> Don't forget that we use the pubKey to get the MAC

I think we use symKey for that purpose instead?

> Honestly my approach was to hash the symKey to act as a pubKey

Ok, I will follow your approach then.

**Comment by llbartekll** [comment]
But honestly I do not like to call symKey hash a public Key

> Without it then we are going to change our ECIES implementation

Maybe it is worth it? right now, only v2 is using it and we are still breaking functionality with protocol refactor

**Comment by pedrouid** [comment]
Let's just stick to hashing the symmetric key to be used as public key for now and two weeks from now we can revisit and improve the encryption with something like chacha20-poly1305

**Comment by llbartekll** [comment]
just to give my sample data for encryption/decryption:

```
    static let privateKeyA = Data(hex: "1fb63fca5c6ac731246f2f069d3bc2454345d5208254aa8ea7bffc6d110c8862")
    static let publicKeyA = Data(hex: "ff7a7d5767c362b0a17ad92299ebdb7831dcbd9a56959c01368c7404543b3342")
    static let privateKeyB = Data(hex: "36bf507903537de91f5e573666eaa69b1fa313974f23b2b59645f20fea505854")
    static let publicKeyB = Data(hex: "590c2c627be7af08597091ff80dd41f7fa28acd10ef7191d7e830e116d3a186a")
    static let expectedSharedKey = Data(hex: "0653ca620c7b4990392e1c53c4a51c14a2840cd20f0f1524cf435b17b6fe988c")
```


```

cyphertext: VhkbjHqli8hN0rFbAg==
nonce: cXdlY2ZhYXNkYWRz       // 12bytes
tag: 0w8iwmGjjMu9ayQxNApIbA==       // 16bytes
combined: cXdlY2ZhYXNkYWRzVhkbjHqli8hN0rFbAtMPIsJho4zLvWskMTQKSGw=

symmetricKey = Data(hex: "0653ca620c7b4990392e1c53c4a51c14a2840cd20f0f1524cf435b17b6fe988c")
expected plaintext = "WalletConnect"
```
combined is base64 encoded sealBox(nonce+cyphertext+tag) that is send over the relay network

**Comment by dukevantreta** [comment]
Can we close this issue? @chadyj @pedrouid
