### ISSUE TITLE
Handling requests authorisation with namespaces

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/walletconnect-specs#40]
# Test cases
Note: Those test cases describe method authorisation, but authorising events should be done in the same manner. 
## 1. Empty namespaces. Receives request with undefined chainId and not matching method

**Namespaces:**
``` json
[
    {
        "chains": [],
        "methods": [],
        "events": []
    }
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someMethod",
        "params" : [{}],
    },
    "chainId": null
}
```
**Should authorize?:**
No

---

## 2. Namespace with no chains defined. Receives request with undefined chainId and matching method

**Namespaces:**
``` json
[
    {
        "chains": [],
        "methods": ["someMethod"],
        "events": []
    }
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someMethod",
        "params" : [{}],
    },
    "chainId": null
}
```
**Should authorize?:**
No

---

## 3. One namespace. Receives request with undefined chainId and matching method

**Namespaces:**
``` json
[
    {
        "chains": ["eip155:1"],
        "methods": ["someMethod"],
        "events": []
    }
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someMethod",
        "params" : [{}],
    },
    "chainId": null
}
```
**Should authorize?:**
No

---

## 4. One namespace. Receives request with defined chainId and matching method

**Namespaces:**
``` json
[
    {
        "chains": ["eip155:1"],
        "methods": ["someMethod"],
        "events": []
    }
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someMethod",
        "params" : [{}],
    },
    "chainId": "eip155:1"
}
```
**Should authorize?:**
Yes

---

## 5. One namespace. Receives request with defined chainId and not matching method

**Namespaces:**
``` json
[
    {
        "chains": ["eip155:1"],
        "methods": ["someMethod"],
        "events": []
    }
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someOtherMethod",
        "params" : [{}],
    },
    "chainId": "eip155:1"
}
```
**Should authorize?:**
No

---

## 6. Namespace with no chains defined. Receives request with defined chainId and matching method

**Namespaces:**
``` json
[
    {
        "chains": [],
        "methods": ["someMethod"],
        "events": []
    }
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someMethod",
        "params" : [{}],
    },
    "chainId": "eip155:1"
}
```
**Should authorize?:**
No

---

## 7. Multiple namespaces with the same method. Receives request with undefined chainId and matching method for both namespaces

**Namespaces:**
``` json
[
    {
        "chains": ["eip155:1"],
        "methods": ["someMethod"],
        "events": []
    },
    {
        "chains": [],
        "methods": ["someMethod"],
        "events": []
    },
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someMethod",
        "params" : [{}],
    },
    "chainId": null
}
```
**Should authorize?:**
No

---

## 8. Multiple namespaces with different methods. Receives request with defined chainId and matching method for one namespace

**Namespaces:**
``` json
[
    {
        "chains": ["eip155:1", "eip155:137"],
        "methods": ["someMethod"],
        "events": []
    },
    {
        "chains": ["eip155:1"],
        "methods": ["someOtherMethod"],
        "events": []
    },
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someOtherMethod",
        "params" : [{}],
    },
    "chainId": "eip155:1"
}
```
**Should authorize?:**
Yes

---

## 9. Multiple namespaces with different methods. Receives request with defined chainId and matching method for one namespace

**Namespaces:**
``` json
[
    {
        "chains": ["eip155:1", "eip155:137", "cosmos:cosmoshub-4"],
        "methods": ["someMethod"],
        "events": []
    }
]
```
**Incoming SessionRequest:**
``` json
{
    "request" : {
        "method" : "someMethod",
        "params" : [{}],
    },
    "chainId": "cosmos:cosmoshub-4"
}
```
**Should authorize?:**
Yes. But this structure is not encouraged

---

**Comment by dukevantreta** [comment]
On number 9, `"cosmos-cosmoshub4"` chain ID is not conforming to CAIP-2

**Comment by dukevantreta** [comment]
All 9 cases are now implemented in swift as unit tests. Merged in [pull request WalletConnect/walletconnect-docs#180](https://github.com/WalletConnect/WalletConnectSwiftV2/pull/180).

**Comment by Elyniss** [comment]
Today we decided that requests and events cannot have null/empty chainId. Hence test cases: WalletConnect/walletconnect-specs#152, WalletConnect/walletconnect-specs#7 should no longer be authorised.

**Comment by Elyniss** [comment]
This document is no longer valid due to overall protocol improvements
