### ISSUE TITLE
Pairing active/inactive

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/walletconnect-specs#9]
Pairing is considered to be an `inactive` and to initially have (when created on proposer) 5min expiry time. 
Proposer extends pairing to **30 days(or by 30?)** when a `wc_sessionPropose` either error or response is received on inactive pairing topic.

When we consider a pairing as active on `Responder`? 
if right after URI reaches a pairing engine, what if dapp crashes or is "dismissed" before extending its expiry? pairing on wallet will live for 30 days but on dapp will expire on next launch.

if we consider pairing active on responder on first response from dapp which is `wc_sessionSettle` and wallet crashes. We have reversed scenerio where dapp keeps pairing for 30 days but wallet can expire it on next launch?

Extend method could solve this problem.  It could be even sdk internal if we do not want to expose this method to client consumer.

@WalletConnect/core-team any thoughts, what is the decision?

**Comment by jakubuid** [comment]
```Extend method could solve this problem. It could be even sdk internal if we do not want to expose this method to client consumer.```
Can you elaborate? Having first scenario when dApp crashes, where actually do you want to call extend?

**Comment by llbartekll** [comment]
1. Dapp could call `extend` and optimistically extend expiry
2. dapp crashes
3. wallet respond success
4. dapp relaunches and both peers have active pairing

at the same time I am not saying that I am supporting this approach more then others just want to discuss.

Problem would appear here if wallet crashes and response never comes to dapp but dapp behave optimistically. This could be handled I believe but logic is growing unnecessarily then.

**Comment by jakubuid** [comment]
I see. So sending extend optimistically, what is the purpose of inactive and active pairing then?
If we agree on extending from 5min to 30days just after proposing (dApp) and reaching (wallet) uri, I would say let's jus set expiry to 30 days.
